export const ActionTypes={
    ALL_COUNTRIES:"ALL_COUNTRIES",
    COUNTRY_DETAILS:"COUNTRY_DETAILS",
    GET_CONTINENT:"GET_CONTINENT",
    SORTBY_ALPHABET:"SORTBY_ALPHABET",
    SORTBY_POPULATION:"SORTBY_POPULATION",
    COUNTRYBY_ID:"COUNTRYBY_ID"
    
}